Repository tbouffard/playground-release-drafter-and-gh-pages, pull requests merged in 2020-03, with the labels that each got.

#1 Add release-drafter configuration
  .github/release-drafter.yml
  .github/worflows/realease-management.yml
  .gitignore
  README.md
Labels: chore

#2 Add index doc page
  docs/index.adoc
Labels: documentation

#3 Fix GitHub workflows folder name
  .github/workflows/realease-management.yml
Labels: chore

#4 Improve release-drafter configuration
  .github/release-drafter.yml
Labels: chore

#5 fix release drafter configuration documentation detection
  .github/release-drafter.yml
Labels: chore, documentation

#6 Doc generate gh pages from asciidoctor
  .github/workflows/gh-pages-publishing.yml
  .github/workflows/gh-pages-status.yml
  .gitignore
  README.md
  docs/architecture/page.adoc
  docs/demo.adoc
  docs/how-to.adoc
  docs/index.adoc
Labels: documentation

#8 README: add info about release-drafter
  README.md
Labels: documentation

#9 Showcase app for deployment
  .browserslistrc
  .editorconfig
  .eslintrc.js
  .github/workflows/build.yml
  .gitignore
  README.md
  babel.config.js
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  src/App.vue
  src/assets/logo.png
  src/components/HelloWorld.vue
  src/main.ts
  src/shims-tsx.d.ts
  src/shims-vue.d.ts
  tsconfig.json
Labels: enhancement

#10 Add now configuration file
  now.json
Labels: chore

#12 Doc zeit now usage feedbacks
  .github/workflows/gh-pages-publishing.yml
  README.md
Labels: documentation
